version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27019:27017"  # Different port to avoid conflicts
    volumes:
      - mongo_data_track3:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=admin
    command: mongod --replSet rs0 --bind_ip_all

  auth:
    build: ./auth
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - DB_NAME=${DB_NAME_AUTH:-reminderdb_auth}
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret-change-in-production}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-track3.rule=Host(`auth-track3.localhost`)"
      - "traefik.http.services.auth-track3.loadbalancer.server.port=8000"
    depends_on:
      - mongo

  data:
    build: ./data
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - DB_NAME=${DB_NAME_DATA:-reminderdb_data}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth:8000}
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret-change-in-production}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # Data processing specific environment variables
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-csv,json,xlsx}
      - DATA_RETENTION_DAYS=${DATA_RETENTION_DAYS:-2555}  # 7 years for healthcare
      - ENCRYPTION_ENABLED=${ENCRYPTION_ENABLED:-true}
      # DHIS2 Integration
      - DHIS2_BASE_URL=${DHIS2_BASE_URL:-https://dhis2.dgh.cm}
      - DHIS2_USERNAME=${DHIS2_USERNAME:-admin}
      - DHIS2_PASSWORD=${DHIS2_PASSWORD:-district}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.data-track3.rule=Host(`data-track3.localhost`)"
      - "traefik.http.services.data-track3.loadbalancer.server.port=8000"
    depends_on:
      - mongo
      - auth

  forecast:
    build: ./forecast
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - DB_NAME=${DB_NAME_FORECAST:-reminderdb_forecast}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth:8000}
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret-change-in-production}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # Forecasting specific environment variables
      - DATA_SERVICE_URL=${DATA_SERVICE_URL:-http://data:8000}
      - MODEL_UPDATE_INTERVAL=${MODEL_UPDATE_INTERVAL:-24}  # hours
      - FORECAST_HORIZON_DAYS=${FORECAST_HORIZON_DAYS:-30}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forecast-track3.rule=Host(`forecast-track3.localhost`)"
      - "traefik.http.services.forecast-track3.loadbalancer.server.port=8000"
    depends_on:
      - mongo
      - auth
      - data

  optimization:
    build: ./optimization
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - DATABASE_NAME=${DATABASE_NAME:-inventory_optimization}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth:8000}
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret-change-in-production}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # Optimization specific environment variables
      - FORECASTING_SERVICE_URL=${FORECASTING_SERVICE_URL:-http://forecast:8000}
      - INGESTION_SERVICE_URL=${INGESTION_SERVICE_URL:-http://data:8000}
      - OPTIMIZATION_MODEL=${OPTIMIZATION_MODEL:-linear_programming}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.optimization-track3.rule=Host(`optimization-track3.localhost`)"
      - "traefik.http.services.optimization-track3.loadbalancer.server.port=8000"
    depends_on:
      - mongo
      - auth
      - data
      - forecast
      - redis

  dashboard:
    build: ./tracks/track3/dashboard
    environment:
      - NEXT_PUBLIC_DATA_API_URL=http://data-track3.localhost
      - NEXT_PUBLIC_FORECAST_API_URL=http://forecast-track3.localhost
      - NEXT_PUBLIC_OPTIMIZATION_API_URL=http://optimization-track3.localhost
      - NEXT_PUBLIC_AUTH_API_URL=http://auth-track3.localhost
      - NEXT_PUBLIC_DASHBOARD_TITLE=Blood Bank Dashboard - Douala General Hospital
      - NEXT_PUBLIC_HOSPITAL_NAME=Douala General Hospital
      - NEXT_PUBLIC_REFRESH_INTERVAL=30000
      - NODE_ENV=${NODE_ENV:-development}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-track3.rule=Host(`dashboard-track3.localhost`)"
      - "traefik.http.services.dashboard-track3.loadbalancer.server.port=3003"
    depends_on:
      - data
      - forecast
      - optimization

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_track3:/data
    command: redis-server --appendonly yes

  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "82:80"      # Different port to avoid conflicts
      - "8082:8080"  # Different dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  mongo_data_track3:
  redis_data_track3:
